project_id = "bubnuyyvxedsmeuwkune"

[functions.send-test-drive-notification]
verify_jwt = false

[functions.send-subscription-notification]
verify_jwt = false

[functions.send-customer-notification]
verify_jwt = false

[functions.send-dealer-notification]
verify_jwt = false

[functions.send-dealer-approval-notification]
verify_jwt = false

[functions.send-test-drive-reminder]
verify_jwt = false

[functions.send-price-alert-notification]
verify_jwt = false